#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
# https://docs.gradle.org/current/userguide/gradle_wrapper.html
#

##############################################################################
#
#   Gradle wrapper bootstrap script
#   Downloads and installs the Gradle wrapper JAR if not present,
#   then delegates to the wrapper.
#
##############################################################################

set -e

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
    CYGWIN* )
        cygwin=true
        ;;
    Darwin* )
        darwin=true
        ;;
    MINGW* )
        msys=true
        ;;
    NONSTOP* )
        nonstop=true
        ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Resolve links: $0 may be a link
app_path=$0
while
    APP_HOME=${app_path%"${app_path##*/}"}
    [ -h "$app_path" ]
do
    ls=$( ls -ld -- "$app_path" )
    link=${ls#*' -> '}
    case $link in
      /*)   app_path=$link ;;
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s\n' "$PWD" ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Download the wrapper JAR if it doesn't exist
if [ ! -f "$WRAPPER_JAR" ] ; then
    echo "Downloading Gradle wrapper JAR..."
    WRAPPER_URL="https://raw.githubusercontent.com/gradle/gradle/v8.13.0/gradle/wrapper/gradle-wrapper.jar"
    if command -v curl >/dev/null 2>&1 ; then
        curl -fsSL -o "$WRAPPER_JAR" "$WRAPPER_URL" || die "ERROR: Failed to download Gradle wrapper JAR"
    elif command -v wget >/dev/null 2>&1 ; then
        wget -q -O "$WRAPPER_JAR" "$WRAPPER_URL" || die "ERROR: Failed to download Gradle wrapper JAR"
    else
        die "ERROR: Cannot download Gradle wrapper JAR. Install curl or wget, or run 'gradle wrapper' from a machine with Gradle installed."
    fi
fi

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables
#   * all command line arguments
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$WRAPPER_JAR\"" org.gradle.wrapper.GradleWrapperMain "$@"

exec "$JAVACMD" "$@"
